---
title:
- type: main
  text: Kinematics and Forces
creator:
- role: author
  text: Dennis Evangelista
- role: editor
  text: Dennis Evangelista
date: 2023-06-30
lang: en-US
subject: science
identifier:
- scheme: DOI
  text: doi:10.123456
pubisher: Evangelista and Dog
rights: © 2023 Dennis Evangelista
...
